CREATE TABLE [brownie].[APP_SERVICE] (
    [SERVICE_ID]      NVARCHAR (50)   NOT NULL,
    [SERVICE_NAME]    NVARCHAR (250)  NOT NULL,
    [SERVICE_URL]     NVARCHAR (250)  NULL,
    [SERVICE_TYPE]    NVARCHAR (50)   NULL,
    [OPTIONS]         NVARCHAR (1000) NULL,
    [SERVICE_VISIBLE] NUMERIC (5)     NULL,
    [SYSTEM_ID]       NVARCHAR (50)   NULL,
    [ADD_MAP]         NUMERIC (5)     NULL,
    [ADD_TOC]         NUMERIC (5)     NULL,
    [INDEX_NO]        NUMERIC (5)     NULL,
    [IDENTIFY]        NUMERIC (5)     NULL,
    [UM_FLAG]         VARCHAR (1)     NULL,
    [DISABLE_UM_MGT]  VARCHAR (1)     NULL,
    CONSTRAINT [PK_APP_SERVICE] PRIMARY KEY CLUSTERED ([SERVICE_ID] ASC)
);

